### ISSUE TITLE
Completion by title missing?

### ISSUE THREAD

**Issue by srid** [aca/neuron-language-server#2]
README says

> textDocument/completion(search by **title**/id)

However in practice it only completes by ID. When I type in the title, it doesn't do any completion.

**Comment by aca** [comment]
@srid Can you tell me which lsp client / completion engine you are using?

I created an issue for it in completion-nvim. https://github.com/nvim-lua/completion-nvim/issues/163
Currently based on typed word, server looks for the title/id and respond.
But the completion engine(not lsp client), filters the completion items.

I think It should not, but if all other clients behaves like that, I will make some changes.

**Comment by srid** [comment]
I'm using neovim + coc.vim. You can reproduce my editor executable by running `nix-build` inside https://github.com/srid/nix-config/tree/master/nix/nvim
