### ISSUE TITLE
Zettel titles are displayed as warnings in coc.nvim

### ISSUE THREAD

**Issue by maralorn** [aca/neuron-language-server#5]
I am not sure if this is a bug.

I use nvim with coc.nvim and the number of annotated links counts against the number of warnings in my document.
I think there could be another way seeing that they get displayed as blue annotations, where other tools use a white/grey annotation that does not contribute to warning count. Probably the colors don‘t mean much to you, I just want to say, that I guess that lsp provides different types of annotations and maybe the one you are using might not be the optimal choice. (But this might also be a ui issue of coc.nvim.)

**Comment by aca** [comment]
I understand the situation. But it's working as intended.

It is actually not "warning" but "Information".
LSP diagnostic has 4 severity level and I think you should set Information, hint as non error with lsp client.

```
Information
Hint 
Error 
Warning 
```

I will find a way to configure it with coc nvim and document it later.
\+ I was thinking about adding feature to turn off the diagnostic completely.
