### ISSUE TITLE
nix-build install error on macOS

### ISSUE THREAD

**Issue by bangedorrunt** [aca/neuron-language-server#8]
macos version 10.15.6
neovim 0.5 nightly
<img width="2536" alt="image" src="https://user-images.githubusercontent.com/1514823/92076213-80b3d780-edfd-11ea-920a-3b64bbedf91b.png">

**Comment by aca** [comment]
I'm not familiar of packaging with build. And I don't use it either.
So let me know if it's not fixed.
Thanks for the report.
