### ISSUE TITLE
go-to-definition does not work on ?cf links.

### ISSUE THREAD

**Issue by maralorn** [aca/neuron-language-server#9]
Hey and thank you so much for your previous bug fix (the hyphens in ids).
neuron-language-server is now already a great help in my day-to-day activities.

I noticed a small other issue though: When I have a link of the form `<id?cf>` it correctly annotates the link with the title of zettel `id`, but go-to-definition does only work, when I remove the `?cf`. Otherwise I get a "definition not found" error.

**Comment by aca** [comment]
I will add some tests later on. Thanks.
